### ISSUE TITLE
Exception thrown in language_picker_dialog.dart

### ISSUE THREAD

**Issue by akeblom** [gomgom/flutter_language_pickers#3]
I suddenly get this error thrown when creating a picker-dialog. 

There seems like the type inference is not really working.

```
void initState() {
    final languageList = widget.languagesList ?? defaultLanguagesList;
    _allLanguages =
        languageList.map((item) => Language.fromMap(item)).toList();
    _filteredLanguages = _allLanguages;
    super.initState();
  }
```

when assigning _allLanguages I get a runtime exception telling me that List<dynamic> is not of type List<Language>

If I add a type to the map method it works.
```
_allLanguages =
        languageList.map<Language>((item) => Language.fromMap(item)).toList();
``` 

flutter doctor:
```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.14.6 18G95, locale sv-SE)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
[✓] VS Code (version 1.38.1)
[✓] Connected device (2 available)
```

**Comment by erfanegtfi** [comment]
@gomgom please fix this bug using above solution

**Comment by jabirmayar** [comment]
Still giving me exception:

The following assertion was thrown building IconTheme(color: Color(0xdd000000)):
type 'List<dynamic>' is not a subtype of type 'List<Language>'

**Comment by juangom** [comment]
Here same as @jabirmayar . Also did the fix as @akeblom.

**Comment by gomgom** [comment]
I fix this bug today. Maybe it's because of my poor programming working. Sorry about that and please check my package if there is more problem. thank you. :)
